services:
  - type: web
    name: scouting-app-backend
    env: node
    buildCommand: |
      if [ -d "dist" ]; then mv dist dist_old; fi
      npm install
      npm run build
    startCommand: |
      npx sequelize-cli db:migrate
      npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    buildEnv:
      - key: NODE_ENV
        value: production 