services:
  - type: web
    name: scouting-app-backend
    env: node
    buildCommand: |
      rm -rf dist
      rm -rf node_modules
      npm install
      npm run build
    startCommand: |
      node -e "const { execSync } = require('child_process'); try { execSync('npx sequelize-cli db:migrate', { stdio: 'inherit' }); } catch (error) { console.error('Migration failed:', error); process.exit(1); }" && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        fromDatabase:
          name: pit-scouting-db
          property: connectionString
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false

databases:
  - name: pit-scouting-db
    databaseName: pit_scouting
    plan: free 