services:
  - type: web
    name: pit-scouting-backend
    env: node
    buildCommand: npm install
    startCommand: npm run direct-fix-db && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://andyw:Czgaetrse1jITUVv4B1n62SrYpuuvaz8@dpg-cv9ih4dumphs73egiui0-a/pit_scouting_ztej
      - key: FRONTEND_URL
        value: https://1334pitscouting.vercel.app
      - key: JWT_SECRET
        value: 70409c4d84c1d296fac9dcc4043c713315a1676a3ac11722e9b740ffb99073f729242604cb9f11bac98f3da6e695c8045d7f2b17707ee6be55f653e6d1fbb850 