services:
  - type: web
    name: scouting-app-backend
    env: node
    buildCommand: rm -rf dist && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    buildEnv:
      - key: NODE_ENV
        value: production 