services:
  - type: web
    name: scouting-app-backend
    env: node
    buildCommand: |
      npm install
      npm install --save-dev @types/express @types/cors @types/bcryptjs @types/jsonwebtoken @types/multer @types/node
      npm run build
    startCommand: |
      node -e "const { execSync } = require('child_process'); try { execSync('npx sequelize-cli db:migrate', { stdio: 'inherit' }); } catch (error) { console.error('Migration failed:', error); process.exit(1); }" && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        sync: false
    buildEnv:
      - key: NODE_ENV
        value: production 